module.exports = {
  someSidebar: {
    Introduction: ['getting-started', 'add-to-your-project'],
    Advanced: [
      'advanced/analyze-your-own-components',
      'advanced/customize-component-styling',
      'advanced/ignoring-ada-warnings',
    ],
    ['Components Reference']: [
      'components/a11y-context-provider',
      'components/view',
      'components/flex',
      'components/badge',
      'components/badge-list',
      'components/button',
      'components/divisor',
      'components/modal',
      'components/toggle-section',
      'components/form',
      'components/text-input',
      'components/heading',
      'components/link',
      'components/text',
    ],
    ['Type Reference']: [
      'components/types/theme-provider-props',
      'components/types/accessibility-props',
      'components/types/badge-variants',
      'components/types/button-variant-type',
      'components/types/button-intention-type',
      'components/types/button-size-type',
      'components/types/form-schema',
      'components/types/field',
      'components/types/modal-variant-type',
      'components/types/modal-style',
      'components/types/intentions-type',
      'components/types/pallet-colors',
      'components/types/colors-type',
      'components/types/theme-type',
      'components/types/font-weight-value',
    ],
  },
};
